Removing n_jobs key-value in params due to ValueError.
alueError: Parameter values for parameter (n_jobs) need to be a
sequence(but not a string) or np.ndarray.

This is not required and can be removed.