Update 'sncosmo' to fix ImportError
Error:
    ImportError while importing test module '/home/vsts/work/1/s/test/snclassifier_test.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    test/snclassifier_test.py:4: in <module>
        from snmachine import sndata, snfeatures, snclassifier, example_data
    ../../../miniconda/envs/snmachine/lib/python3.7/site-packages/snmachine/sndata.py:21: in <module>
        import sncosmo
    ../../../miniconda/envs/snmachine/lib/python3.7/site-packages/sncosmo/__init__.py:138: in <module>
        from .bandpasses import *
    ../../../miniconda/envs/snmachine/lib/python3.7/site-packages/sncosmo/bandpasses.py:11: in <module>
        from ._registry import Registry
    ../../../miniconda/envs/snmachine/lib/python3.7/site-packages/sncosmo/_registry.py:5: in <module>

        from astropy.extern import six
    E   ImportError: cannot import name 'six' from 'astropy.extern'

astropy.extern no longer packages six with it. sncosmo v2.1.0 removed
all references to six:

    v2.1.0 (2020-02-25)
    ===================

    - Add ZTF transmission functions

    - Bugfixes

      - Corrected pyproject.toml; should help cases where the wrong numpy
        version was being installed.

      - Remove all references to the six package

      - Fix accidental mutation of ``bounds`` inputs in ``fit_lc`` and
        ``mcmc_lc``.

This upgrade should resolve this issue

REF:

    - https://github.com/hyperion-rt/hyperion/issues/219
    - https://github.com/dnarayanan/powderday/issues/34
    - https://github.com/aplpy/aplpy/issues/443

	modified:   environment.yml