Removing umap-learn package due to numpy conflict
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.12.0
  - umap-learn[version='>=0.3.6']

This package is not required at this time, and versioning can be
resolved when it is decided to be included

    modified:   environment.yml