Provide fallback for undetected tag versioning
If `snmachine` is added to another project using `git submodule add
git@github.com:LSSTDESC/snmachine.git` for example, this will add all
files but will not include the `.git/` folder associated with
`snmachine`, it will simply add a `.git` **file** which is used for
reference in the mother repo (`.git/modules/snmachine`). Thus, when one
attempts to run `pip install .` inside `snmachine` an error is thrown
since there resides no `git` folder in the temporary folder that is
created. See below:
```
$ pip install .
Processing /Users/tallamjr/PhD/projects/plasticc/snmachine
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-req-build-1gg6y6wm/setup.py", line 49, in <module>
        description='Machine learning code for photometric supernova classification'
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "/usr/local/anaconda3/envs/snmachine-plasticc/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-req-build-1gg6y6wm'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-req-build-1gg6y6wm/

```
With the key line being: `LookupError: setuptools-scm was unable to detect version for '/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-req-build-1gg6y6wm'.`
To have the same setting one can simply just `git clone
git@github.com:LSSTDESC/snmachine.git` instead of adding as a submodule,
and then the `git` folder can be found and hence a version established
but the fix proposed here would be to use the `fallback_version` option
that was brought in with version
[`3.2.0`](https://github.com/pypa/setuptools_scm/pull/327/files) of
`setuptools_scm`. This allows one to add a "fallback version" to be
considered if VCS is not detected.

Although this requires a manual update of the version number, this will
only happen upon major releases and occurs in one place only in the
codebase -- it is more to catch edge cases, it would be recommended to
new users to use `git clone ... ` where possible.

This was initially not picked up in testing as
`issue/159/dynamic-versioning` was tested in a standalone setting of a
single repo of `snmachine`

	modified:   setup.py